### ISSUE TITLE
Add support for LCD backlight brightness

### ISSUE THREAD

**Issue by m1dst** [m1dst/Trimble-Thunderbolt-Monitor#1]
There was provision made on the PCB to control the brightness of the LCD.  It should be possible to set a value in the code prior to deployment.

The default should be 100%.

I don't see any sense in creating any kind of UI to manage this as it is likely only set once and left.  It would be just as easy for someone to change the value and redeploy.

**Comment by g4fre** [comment]
Having this feature would be good. setting its value before deployment would work as it will not need to be changed often. My LCD  illuminates the whole shack

**Comment by m1dst** [comment]
This is experimental.  If you find any issues with hanging we should roll this feature back.  It took several hours, around 15 PC hangs and many deployments to get to this state.

Annoyingly it ended up being 6 lines of code.

The biggest issue was instantiating the PWM too early.  I almost gave up as the Netduino would crash for no apparent reason after about 11 seconds.  Eventually with trial an error I found that if I enabled PWM later in the startup, the Netduino didn't crash and stayed stable.

To modify the brightness, open Program.cs and find the following line towards the top of the file...

```
        const byte LcdBrighness = 100;
```

The default is 100.

Good luck.  Please report any issues.
